"""Authorization service: JWT issuing/decoding + role checks."""

from __future__ import annotations

import secrets
from datetime import UTC, datetime, timedelta
from typing import TypedDict

import jwt

from app.config import Settings
from app.domain import Manager, Role
from app.logging import get_logger
from app.repositories.manager_repo import ManagerRepository

logger = get_logger(__name__)


class AuthError(Exception):
    """Raised on invalid or expired credentials."""


class TokenPayload(TypedDict):
    sub: str  # telegram_id
    role: str
    exp: int
    iat: int
    jti: str  # unique token id


# Short-lived login tokens generated by the bot ("magic link" flow).
# {token: (telegram_id, expires_at)}
_login_tokens: dict[str, tuple[str, datetime]] = {}
_LOGIN_TOKEN_TTL_SECONDS = 300


class AuthService:
    """Handle JWT issuance and Telegram-ID → Manager lookups."""

    def __init__(self, settings: Settings, managers: ManagerRepository) -> None:
        self._settings = settings
        self._managers = managers

    # ─── JWT ───
    def issue_token(self, manager: Manager) -> str:
        now = datetime.now(UTC)
        exp = now + timedelta(days=self._settings.jwt_ttl_days)
        payload: dict[str, object] = {
            "sub": manager.telegram_id,
            "role": manager.role.value,
            "exp": int(exp.timestamp()),
            "iat": int(now.timestamp()),
            "jti": secrets.token_urlsafe(16),
        }
        return jwt.encode(payload, self._settings.jwt_secret, algorithm="HS256")

    def decode_token(self, token: str) -> TokenPayload:
        try:
            decoded = jwt.decode(token, self._settings.jwt_secret, algorithms=["HS256"])
        except jwt.ExpiredSignatureError as e:
            raise AuthError("Срок действия токена истёк") from e
        except jwt.InvalidTokenError as e:
            raise AuthError("Недействительный токен") from e
        return TokenPayload(
            sub=str(decoded["sub"]),
            role=str(decoded["role"]),
            exp=int(decoded["exp"]),
            iat=int(decoded["iat"]),
            jti=str(decoded.get("jti", "")),
        )

    async def manager_from_token(self, token: str) -> Manager:
        payload = self.decode_token(token)
        manager = await self._managers.find_by_telegram_id(payload["sub"])
        if manager is None or not manager.active:
            raise AuthError("Менеджер не найден или отключён")
        return manager

    # ─── Magic-link from bot ───
    def issue_login_token(self, telegram_id: str) -> str:
        """Issue a one-time short-lived login token (handed out by the bot)."""
        token = secrets.token_urlsafe(32)
        expires = datetime.now(UTC) + timedelta(seconds=_LOGIN_TOKEN_TTL_SECONDS)
        _login_tokens[token] = (str(telegram_id), expires)
        # Opportunistic cleanup
        self._cleanup_login_tokens()
        return token

    async def exchange_login_token(self, token: str) -> Manager:
        """Exchange a one-time token from `issue_login_token` for a Manager."""
        self._cleanup_login_tokens()
        entry = _login_tokens.pop(token, None)
        if entry is None:
            raise AuthError("Неверный или истёкший код входа")
        telegram_id, _expires = entry
        manager = await self._managers.find_by_telegram_id(telegram_id)
        if manager is None or not manager.active:
            raise AuthError("Доступ запрещён")
        return manager

    @staticmethod
    def _cleanup_login_tokens() -> None:
        now = datetime.now(UTC)
        expired = [k for k, (_, exp) in _login_tokens.items() if exp < now]
        for k in expired:
            _login_tokens.pop(k, None)

    # ─── RBAC ───
    @staticmethod
    def assert_role(manager: Manager, *allowed: Role) -> None:
        if manager.role not in allowed:
            raise AuthError("Недостаточно прав")
